production:

development:
  dir: ./videos
  home:
    videos: 5
  thumbnails:
    amount: 4
    dir: ./.thumbnails
  playlist:
    display:
      - license
      - length
  metadata:
    - name: license
      type: text
      options:
        suggest: true
    - year: number
    - name: studio
      type: text
      options:
        suggest: true
    - genres: taglist
    - commercially_usable: on_off
  providers:
    VideoMetadata: true
    VideoVersion: true
