production:

development:
  dir: ./videos
  thumbnails:
    generate: true
    amount: 3
    dir: ./.thumbnails
  metadata:
   - alternative: text
   - name: rating
     type: range
     options:
      min: 1
      max: 10
   - good: on_off
   - name: type
     type: select
     options:
      values:
       - a
       - b
   - butts: taglist
  providers:
   WatchedStatus: true
   VideoMetadata: true
