production:

development:
  playlist:
    display:
      - license
      - length
  metadata:
    - name: license
      type: text
      options:
        suggest: true
    - year: number
    - name: studio
      type: text
      options:
        suggest: true
    - genres: taglist
    - commercially_usable: on_off
    - studio__name: text
    - studio__founding: number
  providers:
    VideoMetadata: true
    VideoVersion: true
